site_name: Mixins
copyright: Copyright 2024 MicrocontrollersDev

theme:
  # favicon: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
  name: material
  # logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue green
    accent: blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue green
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode

repo_name: Mixins
repo_url: https://github.com/MicrocontrollersDev/Mixins
edit_uri: ../Mixins/edit/main/docs/
extra:
  social:
    - icon: simple/modrinth
      link: https://modrinth.com/user/Microcontrollers
    - icon: simple/curseforge
      link: https://legacy.curseforge.com/members/microcontrollerstv/projects
    - icon: simple/codeberg
      link: https://codeberg.org/MicrocontrollersDev
    - icon: fontawesome/brands/github
      link: https://github.com/MicrocontrollersDev
    - icon: simple/matrix
      link: https://matrix.to/#/!axTNrRSaDlwHtQznCp:matrix.org
    - icon: simple/revoltdotchat
      link: https://rvlt.gg/vNMTy2bw
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rejfv9kFJj
    - icon: simple/mastodon
      link: https://sakurajima.social/@microcontrollers
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Microcontrollers
    - icon: simple/kofi
      link: https://ko-fi.com/microcontrollers

nav:
  - "Welcome":
      - "Overview": "overview.md"
      - "Getting Started": "gettingstarted.md"
  - "General":
      - "Overview": "general/overview.md"
      - "Debug": "general/debug.md"
      - "Method": "general/method.md"
      - "At": "general/at.md"
      - "Ordinal": "general/ordinal.md"
      - "Shift": "general/shift.md"
      - "Shadow": "general/shadow.md"
      - "Unique": "general/unique.md"
      - "Slice": "general/slice.md"
      - "Ducks": "general/duck.md"
      - "Corece": "general/coerce.md"
      - "Psuedo" : "general/pseudo.md"
  - "Default Injections":
      - "Overview": "default/overview.md"
      - "Overwrite": "default/overwrite.md"
      - "Inject": "default/inject.md"
      - "Redirect": "default/redirect.md"
      - "ModifyArg": "default/modifyarg.md"
      - "ModifyArgs": "default/modifyargs.md"
      - "ModifyConstant": "default/modifyconstant.md"
      - "ModifyVariable": "default/modifyvariable.md"
      - "Accessor": "default/accessor.md"
      - "Invoker": "default/invoker.md"
  - "Mixin Extras":
      - "Overview": "mixinextras/overview.md"
      - "ModifyExpressionValue": "mixinextras/modifyexpressionvalue.md"
      - "ModifyReceiver": "mixinextras/modifyreceiver.md"
      - "ModifyReturnValue": "mixinextras/modifyreturnvalue.md"
      - "WrapMethod": "mixinextras/wrapmethod.md"
      - "WrapOperation": "mixinextras/wrapoperation.md"
      - "WrapWithCondition": "mixinextras/wrapwithcondition"
      - "Sugar":
          - "Overview": "mixinextras/sugar/overview.md"
          - "Cancellable": "mixinextras/sugar/cancellable.md"
          - "Local": "mixinextras/sugar/local.md"
          - "Share": "mixinextras/sugar/share.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.saneheaders

plugins:
  - search
  - open-in-new-tab
#  - git-revision-date-localized:
#      enable_creation_date: true
#      fallback_to_build_date: true
#  - git-committers:
#      repository: MicrocontrollersDev/Mixins
#      branch: main
# TODO: set up GH actions to push to cloudflare https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/123#issuecomment-1992734955
